"""Removed dob in User

Revision ID: 0a3397b16591
Revises: 8ec47e55fba9
Create Date: 2025-06-23 11:53:41.713661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3397b16591'
down_revision = '8ec47e55fba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photoURL', sa.String(length=512), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('photoURL')

    # ### end Alembic commands ###
