"""Remove photoURL from Question

Revision ID: af180b5e446b
Revises: e0e3ffb910a6
Create Date: 2025-07-31 00:01:59.807397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af180b5e446b'
down_revision = 'e0e3ffb910a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('total_scored',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('remarks',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_scored',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
