"""Change total_scored from Integer to Float

Revision ID: e0e3ffb910a6
Revises: 
Create Date: 2025-07-30 06:09:35.332934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e3ffb910a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
